[build]
  functions = "netlify/functions"

[functions]
  external_node_modules = [
    "express",
    "cors",
    "multer",
    "adm-zip",
    "serverless-http"
  ]
  node_bundler = "esbuild"

[[redirects]]
  from   = "/build-apk"
  to     = "/.netlify/functions/server/build-apk"
  status = 200
  force  = true

[[redirects]]
  from   = "/download/*"
  to     = "/.netlify/functions/server/download/:splat"
  status = 200
  force  = true
